block_labels = ["wip"]
delete_merged_branches = true
status = [
    "Rustfmt",
    "ci (1.59.0, stm32h743)",
    "ci (1.59.0, stm32h753)",
    "ci (1.59.0, stm32h743v)",
    "ci (1.59.0, stm32h753v)",
    "ci (1.59.0, stm32h747cm7)",
    "ci (1.59.0, stm32h7b3)",
    "ci (1.59.0, stm32h7b0)",
    "ci (1.59.0, stm32h735)",
    "ci (stable, stm32h743)",
    "ci (stable, stm32h753)",
    "ci (stable, stm32h743v)",
    "ci (stable, stm32h753v)",
    "ci (stable, stm32h747cm7)",
    "ci (stable, stm32h7b3)",
    "ci (stable, stm32h7b0)",
    "ci (stable, stm32h735)",
]
